version: "3.2"
services:
    db:
      image: mysql:5.7
      restart: always
      expose:
        - "3307"
      volumes:
        - shared_db:/var/lib/mysql # This is sharable DB for all services
        - ./mysql-dump:/docker-entrypoint-initdb.d # auto import for all sql file
      restart: always
      environment: # It creates the MySQL credentials for us, as well as a database called hh. This is the credential you'll need in order for your express app to communicate with the MySQL service. 
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: hh
      ports:
        # Private port for MySQL is 3306 and Public port is 3307. To connect to our MySQL container using Workbench, we use port 3307
        - 3307:3306
    web_app:
      depends_on: # This will tell Docker to start services in dependency order. In this example, before starting the app service, it waits for db to be started.
        - db
      build: ./
      volumes:
        # This maps our host project files to our container's WORKDIR. Whatever changes we make to our local copy, will reflect those changes in WORKDIR.
        - ./src:/var/www/app/src
        - ./package.json:/var/www/app/package.json
      command: npm start
      restart: always
      ports:
        - 3001:3000
volumes: # it means that that specified volume (in this case, db_data) is available to all services (both app and db).
    shared_db: {}